@inline function LV.broyden_banded_model(::LV.ExaModelsBackend, N = 1000; T = Float64, backend = nothing, prod = false, kwargs...)
    n = Int(N)
    c = EM.ExaCore(T; backend = backend, kwargs..., concrete = Val(true))
    EM.@add_var(c, x, N; start = fill(3, N))
    EM.@add_var(c, y, N; start = fill(0, N))
    EM.@add_con(c, LV.broyden_banded_kconstraint(x, k) for k = 1:N÷2)
    EM.@add_con(c, y[1] - LV.broyden_banded_xi(x, 1) - LV.broyden_banded_xi(x, 2))
    EM.@add_con(c, y[2] - LV.broyden_banded_xi(x, 2) - LV.broyden_banded_xi(x, 3) - LV.broyden_banded_xi(x, 1))
    EM.@add_con(c, y[3] - LV.broyden_banded_xi(x, 2) - LV.broyden_banded_xi(x, 3) - LV.broyden_banded_xi(x, 1) - LV.broyden_banded_xi(x, 4))
    EM.@add_con(c, y[4] - LV.broyden_banded_xi(x, 2) - LV.broyden_banded_xi(x, 3) - LV.broyden_banded_xi(x, 1) - LV.broyden_banded_xi(x, 4) - LV.broyden_banded_xi(x, 5))
    EM.@add_con(c, y[5] - LV.broyden_banded_xi(x, 2) - LV.broyden_banded_xi(x, 3) - LV.broyden_banded_xi(x, 1) - LV.broyden_banded_xi(x, 4) - LV.broyden_banded_xi(x, 5) - LV.broyden_banded_xi(x, 6))
    EM.@add_con(c, LV.broyden_banded_yconstraint(y, x, i) for i in 6:N-1)
    EM.@add_obj(c, LV.broyden_banded_objective(x, y, i, T) for i in 1:N)
    return EM.ExaModel(c; prod = prod)
end
