@inline function LV.modified_brown_model(::LV.ExaModelsBackend, N = 1000; T = Float64, backend = nothing, prod = false, kwargs...)
    n = Int(N)
    c = EM.ExaCore(T; backend = backend, kwargs..., concrete = Val(true))
    EM.@add_var(c, x, N; start = fill(-1, N))
    EM.@add_con(c, LV.modified_brown_constraint1(x))
    EM.@add_con(c, LV.modified_brown_constraint2(x))
    EM.@add_con(c, LV.modified_brown_constraint3(x))
    EM.@add_con(c, LV.modified_brown_constraint4(x, n))
    EM.@add_con(c, LV.modified_brown_constraint5(x, n))
    EM.@add_con(c, LV.modified_brown_constraint6(x, n))
    EM.@add_obj(c, LV.modified_brown_objective(x, i, T) for i = 1:N÷2)
    return EM.ExaModel(c; prod = prod)
end
